### ISSUE TITLE
[Bug] Blank Maps

### ISSUE THREAD

**Issue by Nick2bad4u** [MJHylkema/spirit-tree-map#32] opened 2024-10-20 15:38 UTC
As of this morning - Ive been getting a blank map when looking at the Spirit Tree or Wilderness teleport map.

![Example](https://github.com/user-attachments/assets/5254b5aa-2385-450d-bcb1-69acf03bc461)

**Comment by Rikardos87** [comment] 2024-10-23 21:15
Got the same Issue , seems to be a conflict with Better Teleport Menu plugin, Happens to me when I open the teleport menu or using teleports thru the quick teleport menu on Achievement Diary cape. Turning off Better Teleport Menu(wont be fixed if turned on again) or restarting client fixes it.
![image](https://github.com/user-attachments/assets/2c619d76-bbd1-4080-be8e-8ac2ac8c130a)
![image](https://github.com/user-attachments/assets/f014ef5f-d406-49ef-afa7-b383c26b3a0c)
![image](https://github.com/user-attachments/assets/a8fb2e9c-7dc1-49b1-8ae5-83be420f848a)
![image](https://github.com/user-attachments/assets/b7d538bc-c7c6-4c62-9703-9383d461efe6)

**Comment by Nick2bad4u** [comment] 2024-10-25 03:35
> Got the same Issue , seems to be a conflict with Better Teleport Menu plugin, Happens to me when I open the teleport menu or using teleports thru the quick teleport menu on Achievement Diary cape. Turning off Better Teleport Menu(wont be fixed if turned on again) or restarting client fixes it.
> 
> EDIT: Seems its the Expand scroll menu option in Better teleport Menu that causing the issue. ![image](https://private-user-images.githubusercontent.com/65094845/379465088-2c619d76-bbd1-4080-be8e-8ac2ac8c130a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc1NjgsIm5iZiI6MTcyOTgyNzI2OCwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjUwODgtMmM2MTlkNzYtYmJkMS00MDgwLWJlOGUtOGFjMmFjOGMxMzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkODBkOTJlMDU1ZmY4OTAwZmRkYmJkYjUyNDZlYWE3YWJhNzZkMTRlZTA5NTFkMjMzNTdlOGNlN2RiMzFhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TOqLUhtp7HjbAczVSG5xUpnItyB--PJ8mh8ABI8oh0w) ![image](https://private-user-images.githubusercontent.com/65094845/379465175-f014ef5f-d406-49ef-afa7-b383c26b3a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc1NjgsIm5iZiI6MTcyOTgyNzI2OCwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjUxNzUtZjAxNGVmNWYtZDQwNi00OWVmLWFmYTctYjM4M2MyNmIzYTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTU3ZmM5MjAyNjE2YjJmZjQyNWMyNDE2NGRlOGQ2MmQ3YzYyNmYzYzU2YzE0NmM5Njk2NzgyYmRlY2RhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.owQ7-N9uxjcOEvkIud_mSWlvAzAZSEjrzqqU6w2Ngys) ![image](https://private-user-images.githubusercontent.com/65094845/379465443-a8fb2e9c-7dc1-49b1-8ae5-83be420f848a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc1NjgsIm5iZiI6MTcyOTgyNzI2OCwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjU0NDMtYThmYjJlOWMtN2RjMS00OWIxLThhZTUtODNiZTQyMGY4NDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYjkxYzYxNGMyMDRkYWNjYzNkNWNmMGQ2YWZmMDg1ZDdjMzA1NGI3YTRjMjhkYjQ4MjFkMWNmODI3NDE4OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lBkJE49ZPYHefsBmAEAwwtbAU6MjcYQZ1cPdctmcJvU) ![image](https://private-user-images.githubusercontent.com/65094845/379465481-b7d538bc-c7c6-4c62-9703-9383d461efe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc1NjgsIm5iZiI6MTcyOTgyNzI2OCwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjU0ODEtYjdkNTM4YmMtYzdjNi00YzYyLTk3MDMtOTM4M2Q0NjFlZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTA3NmQ5Mzk5MTk0ZjQ0YTEzOGYzZWUyOTVlYzFkNTEzYzg3ZmY4ZGJhOTViNmIwMzVjMTFiMDU2NDFmZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.33nzE5c_gFjvTAb82BYcD2NP3bNkPMjXh9FAqhviwTQ)

thanks for the info

**Comment by MJHylkema** [comment] 2024-10-26 05:48
Thanks for reporting, unfortunately this has been a long standing issue that I can't easily resolve as its due to an interaction with the "Better Teleport Menu" plugin as you are aware. Specifically its the "Expand Scroll Menu" option which is causing a redraw on top of my plugins draws. 

Duplicate of https://github.com/MJHylkema/spirit-tree-map/issues/10

**Closed by MJHylkema** 2024-10-26 05:48 UTC

**Comment by MJHylkema** [comment] 2024-10-26 05:50
Duplicate of #10
