### ISSUE TITLE
Spirit tree map overlapping (still)

### ISSUE THREAD

**Issue by Pixzle** [MJHylkema/spirit-tree-map#12] opened 2023-12-27 11:07 UTC
Spirit tree appears to still be overlapped on different pc's. Saw an old issue posted for this, and dev said will look into it, still same problem 3 weeks later. Just figured I'd bump this.
![image](https://github.com/MJHylkema/spirit-tree-map/assets/154979276/27df20c3-1039-4d76-bc11-ba24bcda989c)

**Comment by Jin-Jiyunsun** [comment] 2023-12-30 22:28
Conflict with the better teleport menu by abex, you need to turn off the menu extender in the plugin

**Comment by MJHylkema** [comment] 2023-12-31 22:06
@Pixzle is this happening on normal worlds or just on League worlds? I could only reproduce this problem if I had previously opened the "fairy mushroom" interface.

**Comment by MJHylkema** [comment] 2024-10-26 05:47
Duplicate of https://github.com/MJHylkema/spirit-tree-map/issues/10

**Closed by MJHylkema** 2024-10-26 05:47 UTC
